'use client'

import Image from "next/image"
import Link from "next/link"
import Accordion from "../components/Accordion"
import { useState } from "react"
import type { Metadata } from "next";
import { usePathname } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Base({
    children
  }: Readonly<{
    children: React.ReactNode;
  }>){
    const [patch, setPatch] = useState(usePathname)
    return(
        <>
            <div className="flex w-full">
                <div className="border-e-2 border-[#1E2D3D] h-full w-fit p-4 space-y-8" id="vertical_enfeite">
                    <Image src={'/icones/console.svg'} width={25} height={25} alt="Console"></Image>        
                    <Image src={'/icones/base.svg'} width={25} height={25} alt="Console"></Image>        
                    <Image src={'/icones/game.svg'} width={25} height={25} alt="Console"></Image>       
                </div>
                <div className="min-w-60 w-fit text-nowrap " id="menu-about">
                    <div></div>
                    <div className="border-e-2 border-[#1E2D3D] h-full divide-y-2 ">
                        <div className="space-y-4">
                            <Accordion title="personal-info" active={patch == '/About' || '/About/Courses' || '/About/Education' ? true : false}>
                               <Link href={'/About'} className={`flex items-center gap-2 p-4 hover:text-[#E99287] transition-colors ${patch == "/About" ? " text-[#E99287]" :  ""}`} >
                                <Image src={'/icones/file.svg'} width={20} height={20} alt="File" />
                                <h1>README.md</h1>
                               </Link>
                               <Link href={'/About/Tech-stack'} className={`flex items-center gap-2 w-full p-4 hover:text-[#43D9AD] transition-colors ${patch == '/About/Tech-stack' ? 'text-[#43D9AD]' : ''} `} >
                                <Image src={'/icones/file.svg'} width={20} height={20} alt="File" />
                                <h1>Tech's Stack</h1>
                               </Link>
                               <Link href={'/About/Education'} className={`flex items-center gap-2 w-full p-4 hover:text-[#3A49A4] transition-colors ${patch == '/About/Education' ? 'text-[#3A49A4]' : ''}`} >
                                <Image src={'/icones/file.svg'} width={20} height={20} alt="File" />
                                <h1>education</h1>
                               </Link>
                            </Accordion>
                            <Accordion title="contacts" active={false}>
                                <Link href={'mailto:nicolasdslira@outlook.com'} className="flex items-center gap-2 w-full p-4 hover:text-[#E99287] transition-colors" >
                                    <Image src={'/icones/email.svg'} width={20} height={20} alt="File" />
                                    <h1 className="text-xs">@Nicolasdslira</h1>
                               </Link>
                            </Accordion>
                        </div>
                    </div>
                </div>
                <div className="divide-y-2 divide-[#1E2D3D] w-full">
                    {children}
                </div>
            </div>
        </>
    )
}